server {
    listen 8080;                 
    server_name Nginx;

    location /api/messages {
        proxy_pass http://messages:8213;
    }

    location /api/other {
        proxy_pass http://other:8214;

    }
}